RNN 으로 영화 리뷰 감정 분석하기
RNN 을 이용하여 IMDB 의 영화 리뷰가 긍정적인지 부정적인지 구분해봅시다.

In [1]:
import os
import sys
import datetime
import argparse
import torch
from torchtext import data, datasets
from torch import autograd
from torch.autograd import Variable
from torch import nn
import torch.nn.functional as F
import copy
import spacy

In [2]:
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

HyperParameter 정의하기

In [3]:
# get hyper parameters
lr = 0.0003
epochs = 8
batch_size = 32

In [4]:
print("\nLoading data...")
TEXT = data.Field(sequential=True,  lower=True)
LABEL = data.Field(sequential=False)
train, test = datasets.IMDB.splits(TEXT, LABEL)
TEXT.build_vocab(train, min_freq=5)
LABEL.build_vocab(train)

train_iter, test_iter = data.BucketIterator.splits(
    (train, test), batch_size=32, shuffle=False, repeat=False, device=-1)




vocab_size = len(TEXT.vocab)
n_classes = len(LABEL.vocab) - 1


Loading data...


IMDB 데이터셋 불러오기

Tockenizing 이 끝난 데이터 하나를 살펴보겠습니다. list of words 로 표현되는 데이터가 positive 혹은 negative 레이블을 띄고 있는것이 확인 가능합니다.

In [159]:
b, batch = (next(enumerate(train_iter)))

# for i in range(0, batch_size):
review = batch.text
sentiment = batch.label
# for i in range(0, batch_size):
print([TEXT.vocab.itos[j] for j in review.data[:,0]] )
print(sentiment.data[0])
#1 is neg, 2 is pos

['i', 'loved', 'this', 'movie.', 'i', 'totally', 'disagree', 'with', 'some', '<unk>', 'critiques', 'that', "i've", 'read', 'over', 'the', 'years.', 'this', 'was', 'a', 'great', 'vehicle', 'for', 'eddie', '<unk>', 'he', 'appeared', 'to', 'have', 'a', 'great', 'time', 'with', 'his', 'part', 'as', 'chandler', '<unk>', 'and', 'he', 'should', 'never', 'care', 'about', 'what', 'the', 'critics', 'say,', 'if', 'he', 'had', 'fun', 'doing', 'it', '\x96', 'and', 'most', 'of', 'his', 'audience', 'enjoyed', 'it!', 'and,', 'it', 'was', 'fun', 'to', 'watch', 'as', 'it', 'combined', 'some', 'great', 'fantasy', 'tension', 'with', 'mr.', "murphy's", 'great', 'comedic', 'style.', 'you', 'have', 'to', 'keep', 'in', 'mind', 'that', '<unk>', "child'", 'is', 'a', '<unk>', 'film', '\x96', 'just', 'an', 'imaginative', 'work', 'of', 'magic', 'and', 'wonder', 'amidst', 'the', "'real'", 'world.', 'during', 'the', 'time', 'this', 'film', 'was', 'released,', 'i', 'was', 'working', 'in', 'a', 'video', 'rental', 'sto

RNN Classifier 객체 정의하기

In [160]:
class BasicRNN(nn.Module):
    def __init__(self, batch_size, vocab_size, embed_dim, hidden_dim, n_classes, dropout=0.2,  n_layers=1):
        super(BasicRNN, self).__init__()
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.hidden_dim = hidden_dim
        self.n_layers = n_layers
        self.batch_size = batch_size
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.gru = nn.GRU(embed_dim, hidden_dim, n_layers)
        self.dropout = nn.Dropout(dropout)
        self.linear = nn.Linear(self.hidden_dim, n_classes)
        
    def forward(self, source_sentence):
        embedded = self.embedding(source_sentence)
        init_h = self.init_hidden(self.batch_size)        
        _, hidden = self.gru(embedded, init_h)
        self.dropout(hidden)
        hidden = hidden.squeeze(0)
        linear = self.linear(hidden)
        return linear

    def init_hidden(self, batch_size):
        hidden = Variable(torch.zeros(self.n_layers, batch_size, self.hidden_dim) )
        return hidden

한 Batch 를 학습하는 함수 구현하기

In [183]:
def train(model, optimizer, train_iter):
    """Train Model"""
    #모델을 train 모드로 바꿔줌
#     criterion = nn.BCEWithLogitsLoss()
    model.train()
    for b, batch in enumerate(train_iter):
        #batch 속의 데이터와 레이블을 전에 정한 기기로 보내줍니다. 
        x, y = batch.text.to(device), batch.label.to(device)

        #레이블을 1,2 에서 1을 빼 0,1 값으로 바꿔줍니다.
        y.data.sub_(1)
        optimizer.zero_grad()

        x = Variable(x)
        y = Variable(y)
        
        logit = model(x).squeeze()

        loss = F.cross_entropy(logit, y)
        loss.backward()
        optimizer.step()
        print("loss at batch ",b, " is ", loss.item() )# %d: %5.2f",%(b, loss.item()) )
#         batch 속의 100번째 데이터 마다 오차와 정확도를 출력합니다.
        if b % 10 == 0:
#             print("Training Loss at ", b, ": ", loss)
            corrects = (torch.max(logit, 1)[1].view(y.size()).data == y.data).sum()
            accuracy = 100.0 * corrects / batch.batch_size
            sys.stdout.write(
                '\rBatch[%d] - loss: %.6f  acc: %.4f (%d/%d)' % (
                b, loss.item(), accuracy, corrects, batch.batch_size))

모델 성능을 평가하는 함수 구현

In [182]:
def evaluate(model, val_iter):
    """evaluate model"""
    model.eval()
    corrects, avg_loss = 0, 0
    for batch in val_iter:
        x, y = batch.text.to(device), batch.label.to(device)
        y.data.sub_(1)
        

        
        logit = None
        try:
            logit = model(x)
        except:
            continue
        loss = F.cross_entropy(logit, y, size_average=False)
        avg_loss += loss.data[0]
        corrects += (torch.max(logit, 1)
                     [1].view(y.size()).data == y.data).sum()
    size = len(val_iter.dataset)
    avg_loss = avg_loss / size
    accuracy = 100.0 * corrects / size
    return avg_loss, accuracy

모델 객체를 생성하고 학습시킵니다.

In [163]:
model = BasicRNN(batch_size, vocab_size, 128, 256, n_classes) #(self, vocab_size, embed_dim, hidden_dim, n_classes, n_layers=1):
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
models = []
for e in range(1, 2):
    try:
        train(model, optimizer, train_iter)
        val_loss, val_accuracy = evaluate(model, val_iter)
    except RuntimeError:
        continue
        
    print("\n[Epoch: %d] val_loss:%5.2f | acc:%5.2f" % (e, val_loss, val_accuracy))
    models.append((e,val_loss, val_accuracy, copy.deepcopy(model)))

loss at batch  0  is  0.5652493834495544
Batch[0] - loss: 0.565249  acc: 100.0000 (32/32)loss at batch  1  is  0.45410099625587463
loss at batch  2  is  0.5111140608787537
loss at batch  3  is  0.21587389707565308
loss at batch  4  is  0.21787601709365845
loss at batch  5  is  0.3344394862651825
loss at batch  6  is  0.21996352076530457
loss at batch  7  is  0.0859660655260086
loss at batch  8  is  0.26749616861343384
loss at batch  9  is  0.09539347141981125
loss at batch  10  is  0.08991160988807678
Batch[10] - loss: 0.089912  acc: 100.0000 (32/32)loss at batch  11  is  0.03961355239152908
loss at batch  12  is  0.11098809540271759
loss at batch  13  is  0.13442201912403107
loss at batch  14  is  0.0903748944401741
loss at batch  15  is  0.056058939546346664
loss at batch  16  is  0.030013248324394226
loss at batch  17  is  0.10722120106220245
loss at batch  18  is  0.10355749726295471
loss at batch  19  is  0.06859183311462402
loss at batch  20  is  0.023878920823335648
Batch[20] - 

loss at batch  164  is  0.00010323867172701284
loss at batch  165  is  2.1082862076582387e-05
loss at batch  166  is  3.083118281210773e-05
loss at batch  167  is  1.857077222666703e-05
loss at batch  168  is  2.5206238206010312e-05
loss at batch  169  is  2.9013359380769543e-05
loss at batch  170  is  7.928466948214918e-05
Batch[170] - loss: 0.000079  acc: 100.0000 (32/32)loss at batch  171  is  3.264181214035489e-05
loss at batch  172  is  6.001932706567459e-05
loss at batch  173  is  5.8356494264444336e-05
loss at batch  174  is  7.768708019284531e-05
loss at batch  175  is  2.140266224159859e-05
loss at batch  176  is  0.00010879071487579495
loss at batch  177  is  6.352380296448246e-05
loss at batch  178  is  2.308665352757089e-05
loss at batch  179  is  9.744651470100507e-05
loss at batch  180  is  3.678338907775469e-05
Batch[180] - loss: 0.000037  acc: 100.0000 (32/32)loss at batch  181  is  3.9344067772617564e-05
loss at batch  182  is  1.8176735466113314e-05
loss at batch  183

loss at batch  325  is  0.26102307438850403
loss at batch  326  is  0.3584638237953186
loss at batch  327  is  0.18770639598369598
loss at batch  328  is  0.34312793612480164
loss at batch  329  is  0.30500680208206177
loss at batch  330  is  0.18869107961654663
Batch[330] - loss: 0.188691  acc: 100.0000 (32/32)loss at batch  331  is  0.4990672171115875
loss at batch  332  is  0.1537095159292221
loss at batch  333  is  0.20676341652870178
loss at batch  334  is  0.14256471395492554
loss at batch  335  is  0.18512524664402008
loss at batch  336  is  0.2887139618396759
loss at batch  337  is  0.06311166286468506
loss at batch  338  is  0.6765438914299011
loss at batch  339  is  0.8747435808181763
loss at batch  340  is  0.1444452702999115
Batch[340] - loss: 0.144445  acc: 96.0000 (31/32)loss at batch  341  is  0.25540226697921753
loss at batch  342  is  0.41495150327682495
loss at batch  343  is  0.0678262859582901
loss at batch  344  is  0.5676963925361633
loss at batch  345  is  0.4297

Batch[650] - loss: 0.000505  acc: 100.0000 (32/32)loss at batch  651  is  0.00030421462724916637
loss at batch  652  is  0.0003417448897380382
loss at batch  653  is  0.0006185882375575602
loss at batch  654  is  0.0002499150868970901
loss at batch  655  is  0.0002828915312420577
loss at batch  656  is  0.00038316898280754685
loss at batch  657  is  0.00028545211534947157
loss at batch  658  is  0.0002749522100202739
loss at batch  659  is  0.0004770187952090055
loss at batch  660  is  0.0002362413506489247
Batch[660] - loss: 0.000236  acc: 100.0000 (32/32)loss at batch  661  is  0.0008134146919474006
loss at batch  662  is  0.0004458077601157129
loss at batch  663  is  0.00044291664380580187
loss at batch  664  is  0.0005767394322901964
loss at batch  665  is  0.00035673039383254945
loss at batch  666  is  0.00028237298829481006
loss at batch  667  is  0.0006395908421836793
loss at batch  668  is  0.000587812508456409
loss at batch  669  is  0.0003067806246690452
loss at batch  670  i

Validation Accuracy 가 가장 큰 모델 저장하기

In [181]:

val_loss, val_accuracy = evaluate(model, test_iter)

/Users/sangjunyum/anaconda/lib/python3.6/site-packages/torchtext-0.2.0-py3.6.egg/torchtext/data/field.py:310: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(arr, volatile=not train)
/Users/sangjunyum/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:17: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


tensor([[    86,     88,     15,     10,     49,      2,      3,     10,
             10,     10,     46,    794,   3783,   5862,     16,      3,
             30,    191,     46,     10,   1780,    371,    760,     39,
              3,     10,    627,     48,     51,      9,    308,   4204],
        [   395,    448,      3,      7,   1246,  29859,     88,     20,
              7,      7,    788,    278,   4285,   6488,   1016,   1468,
              5,      3,     25,      7,     12,  20278,     10,    120,
           8795,      7,      4,      3,  10021,    418,      2,      0],
        [   111,     88,    196,      2,   1503,   1879,     24,      7,
              3,    168,    125,      5,    360,      3,   3847,    117,
              2,   5053,     37,      3,     17,    965,    105,      2,
             24,      3,    867,   1315,     51,     10,   1248,      0],
        [    84,   2019,    376,    745,  13388,     17,      8,   1828,
            495,    807,     62,     89,     17,

tensor([[   190,     87,     12,  ...,      9,     10,     48],
        [   119,      4,     14,  ...,     98,     20,      3],
        [ 24352,      3,   1363,  ...,     11,     62,    917],
        ...,
        [ 24352,     10,      3,  ...,   1195,     11,    978],
        [  3326,     20,     56,  ...,      0,   7102,  10320],
        [  2661,   3922,  34402,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[     9,     10,    108,  ...,   2135,      2,      2],
        [   113,    397,     13,  ...,      5,    976,   1121],
        [    23,    191,    540,  ...,   1304,      5,    321],
        ...,
        [  1448,    463,     84,  ...,     25,    264,      8],
        [    49,   2717,   3552,  ...,  14477,    598,      0],
        [     0,   1045,   3552,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,

tensor([[     9,    485,      2,  ...,      2,     52,     44],
        [   680,      3,    211,  ...,   7504,      7,   1896],
        [    16,     49,     20,  ...,    731,     60,     18],
        ...,
        [   965,     12,     52,  ...,    242,   8399,     64],
        [    12,    166,    262,  ...,      2,     57,     28],
        [   699,    491,    457,  ...,    117,   5764,      0]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     9,   4237,    108,  ...,      9,     49,     33],
        [    39,   5449,     13,  ...,    113,      0,   1151],
        [  1978,      7,  17368,  ...,     23,    168,     65],
        ...,
        [   300,    305,      5,  ...,      0,    503,     60],
        [     6,    207,      2,  ...,  13266,      0,  15601],
        [   922,  11576,  16670,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[     9,     10,      9,  ...,      2,     10,      9],
        [   986,    797,   1008,  ...,     78,     20,     86],
        [    12,      7,      9,  ...,   4513,    297,     98],
        ...,
        [    43,     67,    188,  ...,     70,    197,     28],
        [    44,     10,   1555,  ...,      0,   6457,      0],
        [ 25055,      0,  10673,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[    10,     10,     10,  ...,      9,     10,     10],
        [    20,     24,    134,  ...,     82,     82,      7],
        [     7,      7,     14,  ...,    200,     84,     30],
        ...,
        [     3,      0,   1961,  ...,   1201,    154,      8],
        [   207,     13,    266,  ...,      0,   3196,  33134],
        [ 11576,    711,    664,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,

tensor([[     9,    360,      9,  ...,     10,     19,      9],
        [    61,     17,     98,  ...,   8169,      2,    120],
        [    37,   9473,     12,  ...,   3087,   3883,  38211],
        ...,
        [  1799,   6072,     44,  ...,   7872,     68,     97],
        [   888,     27,     11,  ...,  13415,  21441,   4013],
        [ 17003,      0,   5561,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[    38,     10,      3,  ...,     10,     31,     10],
        [   230,      7,    400,  ...,   3165,      2,      7],
        [    58,      3,    212,  ...,    260,    132,    386],
        ...,
        [    41,      5,  18598,  ...,      6,      7,    203],
        [    71,      2,  41939,  ...,   5668,   9958,   5042],
        [ 23941,   1922,      0,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[  1607,     10,     30,  ...,   4087,     49,      9],
        [  9673,     20,      5,  ...,   3901,   1184,     26],
        [     4,   5032,      2,  ...,   1974,      6,     58],
        ...,
        [    10,     47,      0,  ...,    298,     36,      0],
        [   196,      5,     13,  ...,     35,   1373,  10691],
        [  5035,   1317,  25477,  ...,  27560,    560,      0]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[    16,     44,     10,  ...,      9,      2,   6517],
        [   259,    305,     20,  ...,     14,     20,  12154],
        [    36,     11,    604,  ...,     38,    763,   5840],
        ...,
        [    45,    173,     30,  ...,    466,     13,     13],
        [   400,   1292,    923,  ...,   2466,    711,    711],
        [  2676,    801,      0,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[  8340,     10,     10,  ...,   2565,     10,      9],
        [ 19431,     20,      7,  ...,  23277,     20,     86],
        [     7,      7,     23,  ...,   2465,     90,     61],
        ...,
        [ 40835,      0,      8,  ...,  11671,   5529,     70],
        [   297,    789,      2,  ...,  13415,    487,   7455],
        [ 12016,      0,      0,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,
         0,  0,  0,  0])
tensor([[  1469,      9,      9,  ...,     10,    627,     23],
        [    10,    153,     86,  ...,      7,      0,     58],
        [   407,     12,    118,  ...,     30,     13,     14],
        ...,
        [     6,    163,   1165,  ...,    379,  32531,   7689],
        [   153,    487,   2613,  ...,    139,    162,   6276],
        [     0,      1,      1,  ...,      1,      1,      1]]) tensor([ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    10,   1103,      0,  ...,    523,   5965,     10],
        [     7,     92,      7,  ...,    819,   1531,     20],
        [     3,     24,      3,  ...,   2223,  12573,      7],
        ...,
        [ 14837,     23,  12784,  ...,     16,   1358,     10],
        [ 28631,     16,     16,  ...,      0,  44133,    457],
        [  2607,      0,    933,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[     9,     10,      2,  ...,      3,      0,     10],
        [    98,   1216,   1069,  ...,    315,      7,     20],
        [   216,    272,     11,  ...,     24,     30,    681],
        ...,
        [  2951,     11,     10,  ...,      3,      9,      2],
        [     4,    249,   1974,  ...,    683,    120,    183],
        [  1190,    774,  17770,  ...,   6307,    112,   2006]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[     2,     10,   2076,  ...,     10,    273,     52],
        [   201,     20,      0,  ...,     20,     10,      7],
        [    41,     14,  25430,  ...,     41,    844,     51],
        ...,
        [    47,  10648,   1082,  ...,    259,  25468,     49],
        [    16,     19,     19,  ...,    104,   5514,   1383],
        [  3805,   2676,   5086,  ...,   6795,  36307,   2446]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
         1,  1,  1,  1])
tensor([[    10,    108,    108,  ...,    371,     86,      2],
        [    20,     13,     13,  ...,    164,    395,     24],
        [     7,   3058,   3058,  ...,     43,    111,    763],
        ...,
        [ 41135,      0,      0,  ...,      5,    296,   2458],
        [ 22618,     13,     13,  ...,    293,    112,      0],
        [ 22629,    711,    711,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[   107,     10,    198,  ...,      9,     79,     10],
        [    86,    616,   1926,  ...,   7623,   7946,     20],
        [   520,      7,    176,  ...,   1358,   5173,     14],
        ...,
        [ 25987,      0,    250,  ...,   1147,    167,     60],
        [    13,     31,    472,  ...,      0,    139,      0],
        [  8130,   3805,  18900,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[  1262,    190,   2747,  ...,   9732,      0,      8],
        [     0,    119,   4305,  ...,      6,      7,      2],
        [   659,    284,   5071,  ...,      2,    802,    155],
        ...,
        [     4,    198,      3,  ...,    287,      6,   9157],
        [  2730,    345,    105,  ...,    125,     10,   2775],
        [     0,      0,      0,  ...,   1080,    139,  12480]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[     2,  18980,      0,  ...,     12,     55,    216],
        [  1085,  31108,     10,  ...,    175,      3,    710],
        [   882,      7,      7,  ...,     19,    552,      5],
        ...,
        [ 13540,     22,    750,  ...,      5,    472,      2],
        [    20,    384,      7,  ...,      0,    343,   1097],
        [     0,  30160,  37918,  ...,      0,      0,  14057]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[     0,     99,     23,  ...,    465,    107,      2],
        [     7,     34,      3,  ...,    489,     12,    383],
        [     3,   5496,     97,  ...,   4043,    386,    126],
        ...,
        [    16,     67,    779,  ...,   1808,  12212,     13],
        [  2019,     10,    855,  ...,    112,      0,    711],
        [  4462,   2969,  11036,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,

tensor([[    10,      9,  43788,  ...,      9,      2,     57],
        [  1725,     61,    519,  ...,    147,    383,   1384],
        [   324,    447,     83,  ...,   1238,  12313,      4],
        ...,
        [ 18388,    769,      0,  ...,    575,      8,      0],
        [    13,      2,      0,  ...,     86,   1256,    435],
        [   711,   5030,      0,  ...,   5256,  10194,   1125]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[    46,    190,      9,  ...,      9,      3,      9],
        [   298,    119,     86,  ...,    200,   5796,     98],
        [   275,     10,    363,  ...,     10,   6063,     10],
        ...,
        [    16,      3,      6,  ...,     94,      7,      4],
        [   143,    138,   2852,  ...,    148,    577,   2279],
        [  6994,  33357,   2648,  ...,    112,    521,    560]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    10,      2,     46,  ...,   3656,     10,    310],
        [   386,    571,     10,  ...,      0,     24,      9],
        [   205,    150,     24,  ...,      3,      7,    199],
        ...,
        [    61,    175,     60,  ...,   1808,    280,   3373],
        [   135,    228,     34,  ...,  16986,   1549,    135],
        [  7715,      0,    472,  ...,   2648,  22360,    349]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[    10,     10,     10,  ...,      9,      9,     94],
        [    20,     24,     20,  ...,    586,     86,    296],
        [     7,    141,     14,  ...,      9,    118,      2],
        ...,
        [  5009,   1184,    105,  ...,      2,      5,   5514],
        [  5009,     25,   1072,  ...,     20,    968,   1071],
        [  4519,   1484,   2786,  ...,      0,   4583,   8054]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    12,      9,  18379,  ...,   4702,     44,      2],
        [  3983,    200,      9,  ...,      0,     30,     75],
        [    38,     10,    199,  ...,     10,      5,    458],
        ...,
        [   750,     94,   1010,  ...,   5782,   4300,     18],
        [    12,    296,     32,  ...,  30611,     34,     36],
        [  9639,    112,   9265,  ...,   6199,      0,  20091]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[    10,     10,    145,  ...,     10,     48,    190],
        [    20,     20,     23,  ...,      7,    146,    119],
        [   525,    525,    768,  ...,     30,     10,     10],
        ...,
        [   110,    110,      7,  ...,     73,      6,   9804],
        [    10,     10,     39,  ...,     21,     28,     13],
        [  8568,   8568,    607,  ...,  20228,   7374,    711]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    10,     10,    158,  ...,      8,   1335,      9],
        [     7,     20,     84,  ...,      2,      0,    226],
        [     2,     39,      9,  ...,    431,      0,     34],
        ...,
        [   788,      5,     28,  ...,    223,   1131,  15872],
        [    71,   4900,     51,  ...,    158,    516,      8],
        [ 10043,  23343,      0,  ...,  10517,   4462,      0]]) tensor([ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     3,    786,      0,  ...,      9,     10,     10],
        [   395,      8,  11086,  ...,    120,     20,     24],
        [     5,    111,      7,  ...,      0,    141,    113],
        ...,
        [   181,      4,  21990,  ...,    171,      4,     17],
        [     6,  37987,     13,  ...,    143,    110,      3],
        [  4653,      0,  11964,  ...,   3884,    112,  22981]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[     9,      9,      9,  ...,     10,     56,   1779],
        [   447,     26,     14,  ...,     24,   1049,   1791],
        [   112,     23,   2463,  ...,      7,     61,      7],
        ...,
        [     2,     21,      3,  ...,      3,    355,     56],
        [   196,   1193,   2030,  ...,   3600,    267,     15],
        [  1178,   1043,   1653,  ...,      0,   2152,   9233]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[    37,    819,      2,  ...,      9,     10,   4662],
        [   167,     57,     24,  ...,    372,      7,    240],
        [ 17928,  11465,     14,  ...,      2,      3,    193],
        ...,
        [   153,  26968,     47,  ...,   7750,    173,     88],
        [    12,   2893,      5,  ...,     13,     56,      8],
        [ 10667,  21953,  10354,  ...,      0,   1671,   2276]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[  4076,      2,    109,  ...,      2,      9,      9],
        [  7898,    231,    104,  ...,     20,    200,     26],
        [   113,     11,    100,  ...,   1437,     10,     71],
        ...,
        [    74,     15,     68,  ...,      6,      0,     16],
        [  7056,      3,     39,  ...,      2,     88,     25],
        [   472,   1885,    472,  ...,   1229,     24,   4007]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     9,      9,     10,  ...,     10,      3,      0],
        [    62,    403,      7,  ...,     20,    160,   1573],
        [     6,     35,      3,  ...,   5135,   3348,   1425],
        ...,
        [     3,    197,    542,  ...,   1273,    856,     22],
        [   317,      6,      7,  ...,   2274,      6,  10575],
        [     0,   3788,   1667,  ...,   6125,      0,   6125]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    34,     10,     44,  ...,    240,      9,      9],
        [   855,      7,    549,  ...,   1126,    120,    199],
        [     2,      3,     48,  ...,    119,      2,     11],
        ...,
        [     5,   5375,     31,  ...,   2898,      2,    127],
        [     3,    497,  24647,  ...,   2683,   7130,    388],
        [  9664,   8696,      0,  ...,  20277,   4919,   1226]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     9,      9,      3,  ...,      9,    358,     82],
        [   273,    200,    351,  ...,    584,   4146,      5],
        [     2,     10,      5,  ...,    120,   1090,    364],
        ...,
        [     5,    164,     10,  ...,     25,   1216,    510],
        [   401,     18,     30,  ...,    311,  24939,      5],
        [  2385,   6416,   3435,  ...,   6165,  16876,    112]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    57,     10,      0,  ...,     10,    759,   4159],
        [ 19350,     14,   3214,  ...,     24,     43,      9],
        [    10,     23,  41669,  ...,     14,   2881,     14],
        ...,
        [   274,      2,    105,  ...,      2,    227,    148],
        [   525,    578,   2603,  ...,   2970,      2,     10],
        [   491,   2218,   1667,  ...,   1042,  42910,    117]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[    10,     10,      3,  ...,   8280,      9,     16],
        [    14,     24,     20,  ...,      9,     82,    181],
        [    30,      7,    190,  ...,    273,    273,      9],
        ...,
        [     2,      5,     88,  ...,      0,    422,      7],
        [     0,      2,  27221,  ...,      0,  28369,   1531],
        [ 13688,    117,      0,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[   190,   5833,   1329,  ...,     10,     10,     10],
        [    58,   3507,   1288,  ...,      7,      7,     20],
        [   119,    270,    632,  ...,     32,    371,   1462],
        ...,
        [  1057,    120,      0,  ...,     36,      4,    371],
        [     4,     10,    496,  ...,   7360,    823,    267],
        [     0,   1549,   3276,  ...,      0,   3723,   3887]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     0,   1551,      2,  ...,      0,     10,    108],
        [  5883,    204,   2532,  ...,     48,     14,     13],
        [     5,     29,     53,  ...,     32,      3,   7217],
        ...,
        [    47,      4,     74,  ...,   1385,      3,   1541],
        [     5,     67,   1401,  ...,    241,    105,    910],
        [  1317,   1045,    933,  ...,   7388,  30792,     97]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[   643,      9,     10,  ...,    428,   1952,     15],
        [  6853,    372,     20,  ...,    120,      9,      3],
        [     4,     12,      7,  ...,      6,    120,    376],
        ...,
        [     3,      9,      4,  ...,     16,   4783,   2222],
        [    97,    403,     67,  ...,      3,    483,    300],
        [     0,    112,    661,  ...,  19700,   3388,   2969]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     9,   4090,      9,  ...,    190,     10,      0],
        [   377,      9,    200,  ...,    119,      7,      0],
        [    72,     39,     10,  ...,     39,     30,     44],
        ...,
        [     5,   6181,    267,  ...,      0,    344,     93],
        [   663,     16,      3,  ...,     13,     10,  10631],
        [ 16964,   6056,  34193,  ...,      0,   5866,  14874]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[     2,  30254,      9,  ...,    179,      9,   1787],
        [    82,  32210,     61,  ...,      9,    273,   2785],
        [   462,     15,    372,  ...,   1710,     10,      7],
        ...,
        [    10,   2817,    241,  ...,    173,      2,     97],
        [  1177,      4,    209,  ...,   2547,      0,    139],
        [     0,  20878,  12046,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[   116,      9,      2,  ...,      9,    310,     94],
        [   376,    120,    638,  ...,    200,    347,     99],
        [   523,      0,      5,  ...,     10,     87,    137],
        ...,
        [   152,  12829,     47,  ...,    428,     47,   6514],
        [  2251,      0,      5,  ...,  12478,      5,    496],
        [  8695,   3600,   1317,  ...,      0,      0,   2119]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[  1551,     51,     82,  ...,     94,     52,    192],
        [     9,      5,      2,  ...,    296,     22,     23],
        [    54,      3,    791,  ...,    196,    129,      3],
        ...,
        [     2,      4,    312,  ...,     11,     84,     37],
        [   238,   7405,     10,  ...,     25,     41,    955],
        [   139,      0,   2181,  ...,  10115,   4653,  33202]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         1,  1,  1,  1])
tensor([[     9,     48,    190,  ...,      0,      0,   4259],
        [    14,      3,    273,  ...,     36,      0,     10],
        [   275,   2116,     10,  ...,      8,      7,     14],
        ...,
        [    12,   1377,      8,  ...,    197,   5183,     10],
        [     3,    123,    111,  ...,      2,      0,   1071],
        [  3611,   2119,      0,  ...,  37554,      0,   4471]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[ 12297,      2,      3,  ...,      9,     46,     79],
        [     0,     58,     49,  ...,    200,     25,     76],
        [     0,     56,   3135,  ...,     10,     22,     85],
        ...,
        [     5,     20,     13,  ...,      8,     10,      9],
        [     3,     14,   7577,  ...,      0,    457,   1169],
        [ 30810,  25621,    107,  ...,      0,  13034,  11791]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[     2,      0,     10,  ...,  29235,      0,      9],
        [    20,   1850,     24,  ...,     10,     10,    128],
        [   458,      2,     14,  ...,     20,     14,     26],
        ...,
        [     8,    204,      4,  ...,     26,    107,     82],
        [     2,    110,  33205,  ...,     71,    267,   1722],
        [  1213,     12,      0,  ...,   1626,    112,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[   166,     10,    100,  ...,      9,      9,    795],
        [    29,    134,    286,  ...,     26,     39,      0],
        [     2,     64,      2,  ...,   4573,    176,     31],
        ...,
        [    87,    416,     35,  ...,    110,    604,      3],
        [     9,      7,      2,  ...,      4,    137,    152],
        [  9623,    774,    704,  ...,   3788,   1494,      0]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     3,     50,      9,  ...,      8,      9,    108],
        [   400,  11793,     64,  ...,   3875,    120,     13],
        [     0,      0,    451,  ...,  14891,  12189,      0],
        ...,
        [    47,    785,     61,  ...,    406,     47,     16],
        [     5,    381,   2116,  ...,    191,      5,      2],
        [  1317,   7755,    117,  ...,      0,   1317,   3447]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[     2,    227,   8280,  ...,      9,      0,   4159],
        [    82,      2,      2,  ...,    200,   2406,      9],
        [   174,      0,     58,  ...,     10,   2406,     26],
        ...,
        [ 18969,      7,     15,  ...,  11382,      0,  19872],
        [     0,    168,      2,  ...,     13,  16622,      0],
        [ 13415,  37947,  18445,  ...,      0,      0,   6481]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[     9,      2,   9762,  ...,      2,     12,     10],
        [    98,    462,      7,  ...,     20,      7,   5626],
        [    11,    763,     32,  ...,      7,   1982,    225],
        ...,
        [    12,   4795,    207,  ...,      2,     19,      4],
        [     7,   8504,     67,  ...,     20,     35,   9166],
        [     0,      0,      0,  ...,    138,  33671,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[    16,      9,      9,  ...,    113,      0,     32],
        [    35,     64,   1169,  ...,     25,      7,   2392],
        [ 21634,     67,     10,  ...,    125,     30,      6],
        ...,
        [   110,      6,    204,  ...,     25,     26,     85],
        [    10,     85,    189,  ...,    857,   1609,     12],
        [ 10959,    464,   4680,  ...,    464,    801,   1867]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[  1356,     10,     48,  ...,      8,     52,    100],
        [ 21564,     20,     41,  ...,     57,      7,     89],
        [    15,     14,   1790,  ...,    210,      3,    346],
        ...,
        [ 16388,   3054,      2,  ...,    498,     47,     37],
        [  1439,      6,   7702,  ...,    190,      5,  30663],
        [  6758,  21272,      0,  ...,    705,   1317,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[    10,     10,      9,  ...,      9,    565,    782],
        [ 10876,   4070,    102,  ...,    147,   2476,   8322],
        [    20,      7,    200,  ...,    779,    482,      4],
        ...,
        [     2,      3,     46,  ...,      0,   4397,     16],
        [ 22854,   5380,     25,  ...,  44954,  18270,   8731],
        [     0,   5436,  22506,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[     9,      0,      3,  ...,      9,      9,      9],
        [   120,    106,      0,  ...,    273,    200,     61],
        [     2,     85,   6562,  ...,     10,     10,     61],
        ...,
        [    58,  19975,    490,  ...,      2,      5,      5],
        [   130,    278,      0,  ...,    211,     10,   3662],
        [   560,   1693,      0,  ...,   2181,    117,   2934]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    94,      8,    310,  ...,      2,    179,     10],
        [     9,     57,      9,  ...,   1112,    296,      7],
        [   308,   1691,     26,  ...,      5,     10,      3],
        ...,
        [     0,     12,      3,  ...,      6,      5,   4927],
        [    70,      6,     56,  ...,     73,  17109,     69],
        [ 16089,    718,   2852,  ...,   1045,  13844,   1484]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[    46,     10,   1070,  ...,   1279,     10,      9],
        [    25,    797,     46,  ...,   8372,     24,    325],
        [   180,    956,      9,  ...,    270,     41,      6],
        ...,
        [  7101,    508,      0,  ...,      5,     13,     65],
        [  6520,      2,   1790,  ...,      2,  21046,      4],
        [     0,    139,   1065,  ...,  45097,    483,      0]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[   190,    775,   2795,  ...,    232,     10,     57],
        [   119,   9355,      0,  ...,      5,     20,   4152],
        [    10,     15,     41,  ...,      3,     41,     17],
        ...,
        [   377,    896,   3896,  ...,     48,    356,  38255],
        [     0,     12,      5,  ...,      3,      0,      4],
        [ 24588,    653,    657,  ...,      0,    704,  27547]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     0,      9,     10,  ...,      9,   6002,    220],
        [     0,     26,     20,  ...,     39,      2,     77],
        [   128,      6,      7,  ...,    486,    770,     10],
        ...,
        [    19,     31,     12,  ...,     12,   6565,     26],
        [     0,      2,     14,  ...,     61,   2061,     57],
        [     0,      0,   2262,  ...,  25691,  15106,      0]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    55,   1612,      0,  ...,      9,     10,    296],
        [   192,    483,     13,  ...,    365,      7,     10],
        [    10,     16,    255,  ...,    148,     23,    151],
        ...,
        [    24,     12,     14,  ...,    123,     93,     33],
        [     9,      7,    104,  ...,     37,  10631,   3666],
        [ 12495,  23941,  15730,  ...,    464,  14874,     87]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[    44,     30,     10,  ...,     10,    934,     38],
        [   235,      5,      7,  ...,     14,    347,     76],
        [    77,      2,     30,  ...,      3,     87,     88],
        ...,
        [    95,      6,      4,  ...,   1148,   1748,    138],
        [    87,    265,   7896,  ...,   3966,    629,   1566],
        [  9289,   2006,   2191,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[ 38142,  38142,     10,  ...,      8,      9,   1644],
        [     0,      0,     24,  ...,     10,     26,     34],
        [     6,      6,     14,  ...,   1622,     71,      2],
        ...,
        [    72,     72,  12534,  ...,    195,      7,     68],
        [  3471,   3471,  24414,  ...,     57,    267,     12],
        [  2309,   2309,   3100,  ...,  35502,   1045,  10162]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     9,     31,     10,  ...,     10,    189,   5332],
        [   226,  29806,      7,  ...,      7,      2,  26585],
        [  3929,    385,    167,  ...,      3,    238,    533],
        ...,
        [  6237,    276,    260,  ...,      0,    104,      2],
        [    43,     11,     12,  ...,  10785,      0,   1284],
        [     0,   3768,  32825,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[    32,   5603,      3,  ...,      0,    158,      9],
        [   552,    328,    534,  ...,      5,     20,     58],
        [  7835,  11439,      5,  ...,      2,      9,   1000],
        ...,
        [    10,     33,  10321,  ...,      2,   9970,     84],
        [   157,    377,     64,  ...,      0,     87,     19],
        [  2998,   4256,   5392,  ...,   5979,      0,    112]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[   795,      9,   1145,  ...,     16,     10,      9],
        [ 14087,    120,   1644,  ...,   1353,      7,    584],
        [   344,     10,      2,  ...,      9,    167,     86],
        ...,
        [   555,    148,      7,  ...,   1390,    917,     16],
        [   563,   7843,      3,  ...,   9553,      0,    933],
        [   112,  18781,   5084,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,

tensor([[    58,     10,    281,  ...,     12,      0,   5484],
        [     3,      7,    100,  ...,     54,    110,   3848],
        [    49,   4524,     26,  ...,    268,     12,    287],
        ...,
        [   195,      2,     47,  ...,      7,    136,     16],
        [     3,      0,      5,  ...,    126,    129,   8478],
        [     0,      0,   2342,  ...,      0,   1410,   3100]]) tensor([ 0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     0,    528,     94,  ...,    627,      3,      9],
        [     7,    394,    855,  ...,    590,   1725,    199],
        [   386,     19,      2,  ...,    334,  12028,     11],
        ...,
        [    11,     59,    111,  ...,      3,   2742,   1550],
        [     9,      0,    481,  ...,      0,  33864,   8649],
        [ 15964,      0,   1311,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,

tensor([[  1070,      9,     79,  ...,      2,   2965,   3070],
        [    43,     86,     64,  ...,  26535,     10,  29828],
        [   607,    118,     92,  ...,   7689,      3,  40429],
        ...,
        [ 16993,     67,     24,  ...,   1326,     57,  32163],
        [  1405,      2,      7,  ...,     16,    329,     23],
        [  5265,    692,  19661,  ...,   2934,   1693,   1915]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  1])
tensor([[    48,     10,      9,  ...,     16,     69,    145],
        [  1073,     20,    120,  ...,      3,    989,    162],
        [   312,      7,   1090,  ...,     20,      8,      6],
        ...,
        [     0,     26,     35,  ...,      5,     32,     49],
        [    13,     57,    127,  ...,    845,    791,   1577],
        [ 11359,  35229,    664,  ...,  23462,   7855,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,

tensor([[  5700,      3,     10,  ...,      0,      9,     76],
        [   584,    160,    616,  ...,      0,    680,     64],
        [ 15954,      7,      7,  ...,    186,   8381,    584],
        ...,
        [ 12997,      6,     49,  ...,    741,    326,      0],
        [    13,    991,     56,  ...,  17816,      0,  12806],
        [     0,   1761,    801,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[    39,      2,      2,  ...,   1551,      9,    444],
        [  1978,    258,     82,  ...,   1894,    178,      0],
        [   148,    875,     24,  ...,      9,    363,      2],
        ...,
        [    40,   3383,    800,  ...,    606,      3,    198],
        [   110,    208,      5,  ...,   1583,    138,      4],
        [  1045,   1693,   1405,  ...,  19072,      0,    929]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[    10,  16006,   6822,  ...,     19,     52,     82],
        [    95,      9,     30,  ...,     59,     14,      5],
        [    16,   1169,     61,  ...,    109,      3,    364],
        ...,
        [     2,    520,     44,  ...,   1111,     39,     92],
        [   332,    104,      3,  ...,     99,   1561,     80],
        [  6582,   1267,   4077,  ...,   1208,      0,   7795]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[ 19889,  25246,    428,  ...,      9,      0,  29836],
        [    64,     74,   1520,  ...,    120,      7,      0],
        [ 35509,    102,     10,  ...,   1301,      3,      0],
        ...,
        [    23,  24247,    127,  ...,      2,    349,    407],
        [  3364,    138,     45,  ...,      0,     10,      5],
        [ 12681,   9697,      0,  ...,      0,    117,   8462]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[   446,    627,      2,  ...,      0,     82,     10],
        [   275,      0,    256,  ...,      3,      5,    462],
        [  8030,     24,   4275,  ...,    975,    284,     62],
        ...,
        [    73,      0,     43,  ...,  26475,    103,      0],
        [    51,     13,    179,  ...,      0,    723,  13057],
        [  7877,   8278,  40867,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[     9,      9,     30,  ...,  27421,    963,      0],
        [    86,   1126,      5,  ...,     51,    850,      7],
        [   363,   1169,      2,  ...,     68,   1346,      3],
        ...,
        [  1254,    320,     10,  ...,     56,    923,    207],
        [    88,      8,     88,  ...,  42029,   2385,   1850],
        [   139,  42425,    117,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,

tensor([[  8412,    310,   1716,  ...,     52,     10,     35],
        [ 42741,     16,   1039,  ...,      7,     20,      2],
        [   113,     10,     41,  ...,     60,     14,    109],
        ...,
        [  2308,    407,    628,  ...,     97,    267,      3],
        [    61,      5,      8,  ...,    117,      0,  25035],
        [  3276,   3228,   2966,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,
         0,  0,  0,  0])
tensor([[    10,      9,     10,  ...,      9,      2,      8],
        [    24,     82,     24,  ...,    153,   4237,      2],
        [    41,    510,   1425,  ...,      0,    599,    224],
        ...,
        [ 24387,     25,   1658,  ...,      6,      5,    332],
        [     3,   1525,     12,  ...,   7403,    401,  24806],
        [  7231,   5905,  10183,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,

tensor([[     9,     10,     49,  ...,      3,      3,      9],
        [   365,     14,  11603,  ...,    169,    169,    184],
        [   148,      3,     18,  ...,     43,     43,     10],
        ...,
        [     9,      3,    998,  ...,    206,    206,      0],
        [    64,   1148,    470,  ...,     28,     28,     13],
        [  9412,  10696,    473,  ...,  16476,  16476,    711]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[     0,  43054,      0,  ...,    475,     10,     15],
        [  2719,   4191,      7,  ...,    342,   1291,   1292],
        [   103,   1409,     10,  ...,      0,     45,      4],
        ...,
        [  1025,     13,   1802,  ...,  12545,     30,     34],
        [     2,  11365,      7,  ...,      4,   6287,    472],
        [  4295,      0,      0,  ...,      0,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,

tensor([[     2,    192,    435,  ...,     10,     44,    145],
        [    20,      2,  12764,  ...,     20,      3,      3],
        [  2013,    241,     70,  ...,     14,   1273,    376],
        ...,
        [    19,      2,   2723,  ...,     12,      8,     57],
        [     0,   2831,     13,  ...,     11,  30452,  38848],
        [  2969,   1599,      0,  ...,      0,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  0,  0])
tensor([[  1551,     32,     10,  ...,     15,     82,     48],
        [    82,    299,     24,  ...,      3,      5,    549],
        [   137,    523,     14,  ...,    218,    364,      7],
        ...,
        [     6,     28,     74,  ...,      0,    978,  10324],
        [    10,     45,    779,  ...,      0,   5470,   2630],
        [   457,   9166,    112,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,

tensor([[   145,     10,      2,  ...,      2,     50,      9],
        [     3,   2078,     82,  ...,    904,      0,    365],
        [   376,      7,  32595,  ...,   2402,      3,    148],
        ...,
        [   623,     34,     29,  ...,     17,   2630,     16],
        [    12,    111,     17,  ...,     10,   5042,   4007],
        [ 19284,   8989,   2642,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  1,  1,  1])
tensor([[  1952,     32,  40032,  ...,     10,     10,  10543],
        [    38,    299,     48,  ...,     20,   2078,      0],
        [    12,    256,     64,  ...,      7,      7,      7],
        ...,
        [     3,   6180,    250,  ...,    914,    111,     13],
        [  2404,  10486,   1045,  ...,   3884,   8989,   6921],
        [  8352,      0,      0,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

tensor([[ 19350,      2,      9,  ...,      0,     10,     30],
        [     9,     20,    118,  ...,   2768,      7,      5],
        [   226,  29591,    105,  ...,  23090,      3,    465],
        ...,
        [   314,      6,   6382,  ...,      0,   4136,   3882],
        [     0,   1706,      8,  ...,      1,      1,      1],
        [ 26125,    560,    112,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  0,  0,  0])
tensor([[   164,      9,     46,  ...,     50,   5589,     10],
        [    37,     26,     25,  ...,     12,    298,     24],
        [    10,     45,    311,  ...,     14,     65,      7],
        ...,
        [     5,      3,    886,  ...,   5561,      0,  12187],
        [  2180,     88,     12,  ...,      1,      1,      1],
        [  1599,   2268,  10799,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1,

tensor([[     9,     46,     94,  ...,  29540,     83,      0],
        [  1041,   5718,    855,  ...,  24582,    130,    378],
        [    11,     15,      2,  ...,   7005,      3,  11839],
        ...,
        [    29,    572,      4,  ...,  34902,     30,   1358],
        [    35,    123,    349,  ...,    472,   1405,      0],
        [  9526,   2222,    112,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  1,  1])
tensor([[     0,   3039,  11825,  ...,     16,      9,      9],
        [     7,      0,      5,  ...,      3,     74,     64],
        [     3,      9,      0,  ...,    133,   6560,     58],
        ...,
        [    86,     51,     62,  ...,   1763,   5092,   6775],
        [   741,   3793,     12,  ...,      1,      1,      1],
        [   112,   1810,    801,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,

tensor([[ 43054,     45,     10,  ...,    347,     50,    707],
        [  1231,      0,     20,  ...,     87,      3,      2],
        [     9,      3,     62,  ...,    915,    522,    100],
        ...,
        [   232,      7,  42205,  ...,   6534,   9835,   2661],
        [     5,      3,  11313,  ...,      1,      1,      1],
        [   117,  23003,    801,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  0,
         0,  0,  0,  0])
tensor([[    76,    145,     10,  ...,    103,     15,    100],
        [     5,   2726,     20,  ...,     89,      9,   2144],
        [     2,    243,      7,  ...,    562,    346,    268],
        ...,
        [   164,    411,    923,  ...,    163,      5,   3848],
        [   125,    411,    932,  ...,   4013,   2342,  28594],
        [  2998,    411,      0,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,

tensor([[    10,    190,      2,  ...,     50,   7006,   6495],
        [     7,    206,   5431,  ...,      2,   2227,   7213],
        [     3,    447,      5,  ...,    822,      0,      7],
        ...,
        [   128,   6267,      3,  ...,    897,      0,  11081],
        [   758,      5,     56,  ...,      1,      1,      1],
        [  1586,  11642,    117,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,
         0,  0,  1,  1])
tensor([[    50,   7464,      9,  ...,      9,    106,     52],
        [ 15729,   4220,     39,  ...,     39,     19,      7],
        [   769,   9295,    273,  ...,    273,   1039,     23],
        ...,
        [     0,  16669,   2294,  ...,    117,    472,      0],
        [    47,    181,   1727,  ...,      1,      1,      1],
        [     0,   3090,    139,  ...,      1,      1,      1]]) tensor([ 0,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,

tensor([[    12,      0,   3955,  ...,      3,     16,   1378],
        [    14,      5,    181,  ...,    160,     87,      0],
        [    19,      0,   2760,  ...,    239,     44,      7],
        ...,
        [     5,    223,     51,  ...,      0,   4764,   1317],
        [     0,      0,   1727,  ...,      1,      1,      1],
        [  4462,   8507,   8462,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,
         0,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0])
tensor([[  4852,     46,     15,  ...,   2394,     50,  18679],
        [     0,     25,      3,  ...,      4,    148,      0],
        [   391,    308,  33330,  ...,  22805,     10,    146],
        ...,
        [   112,   3108,     54,  ...,    139,      0,  12732],
        [     3,     29,     26,  ...,      1,      1,      1],
        [  5374,      0,      0,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  0,

tensor([[   216,      2,   5894,  ...,   2109,      9,     12],
        [   143,    196,    413,  ...,  37976,     74,    485],
        [  2130,    461,      5,  ...,      0,   4830,      3],
        ...,
        [     2,     20,    127,  ...,   8997,  13099,   1858],
        [ 23559,      7,    198,  ...,      1,      1,      1],
        [     0,   1230,  36241,  ...,      1,      1,      1]]) tensor([ 0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,
         1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,
         1,  1,  1,  1])
tensor([[    94,      9,      2,  ...,     46,      0,   4220],
        [     2,     26,    284,  ...,     25,     70,   5834],
        [  1307,     71,   5853,  ...,    102,     10,    738],
        ...,
        [  1466,      5,   1442,  ...,      1,      1,      1],
        [    31,  14206,   2852,  ...,      1,      1,      1],
        [     0,      1,      1,  ...,      1,      1,      1]]) tensor([ 1,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,

tensor([[ 14590,      0,     16,  ...,    980,      9,      0],
        [   564,    291,      3,  ...,     73,    365,  38881],
        [   103,    168,    904,  ...,     10,    296,   7579],
        ...,
        [    13,      6,   4499,  ...,      1,      1,      1],
        [  8278,    161,      4,  ...,      1,      1,      1],
        [     0,    664,   2240,  ...,      1,      1,      1]]) tensor([ 1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,
         1,  1,  1,  1])
tensor([[    10,    385,     44,  ...,     10,      9,      0],
        [   252,     74,   2450,  ...,      7,   1520,  22271],
        [     7,    596,     11,  ...,      3,     10,    108],
        ...,
        [    13,      4,      8,  ...,      1,      1,      1],
        [   742,     91,     92,  ...,      1,      1,      1],
        [  7152,  14639,    139,  ...,      1,      1,      1]]) tensor([ 0,  0,  0,  0,  0,  1,  1,  0,  1,  1,  1,

tensor([[     0,      9,   1264,  ...,    102,   5011,      0],
        [     8,    698,    980,  ...,     71,   3728,      7],
        [     0,    563,    623,  ...,  17745,     41,     32],
        ...,
        [     5,    509,      8,  ...,      1,      1,      1],
        [    35,    335,      2,  ...,      1,      1,      1],
        [   293,    112,   2440,  ...,      1,      1,      1]]) tensor([ 0,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  0,  0,  1,
         1,  1,  0,  0,  0,  1,  1,  1,  1,  0,  0,  1,  1,  0,
         0,  1,  1,  1])
tensor([[    40,    281,  29235,  ...,  35941,  24435,      0],
        [   288,     83,      2,  ...,      0,  10441,   2405],
        [  1230,    131,    225,  ...,    284,   1498,      0],
        ...,
        [    40,      0,      0,  ...,      1,      1,      1],
        [   288,   5313,      1,  ...,      1,      1,      1],
        [  1230,      1,      1,  ...,      1,      1,      1]]) tensor([ 1,  0,  0,  1,  1,  0,  0,  0,  0,  1,  1,

tensor([[    12,     55,  14340,  ...,   1952,   4749,     30],
        [   141,     17,     14,  ...,     25,      8,      5],
        [   783,     35,      3,  ...,   9923,     63,      2],
        ...,
        [     0,    190,   5400,  ...,      1,      1,      1],
        [    13,    125,  21082,  ...,      1,      1,      1],
        [     0,    705,      1,  ...,      1,      1,      1]]) tensor([ 1,  1,  0,  0,  1,  0,  0,  1,  1,  1,  0,  0,  1,  1,
         1,  0,  0,  0,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,
         1,  0,  1,  1])
tensor([[  1952,      8,      0,  ...,      3,    501,      3],
        [   224,    652,      0,  ...,   2037,     50,    185],
        [  1947,      6,      0,  ...,   2911,      9,    921],
        ...,
        [     3,      7,    229,  ...,      1,      1,      1],
        [  7811,     23,     84,  ...,      1,      1,      1],
        [ 11265,    607,   9455,  ...,      1,      1,      1]]) tensor([ 0,  0,  1,  1,  1,  1,  1,  0,  0,  1,  0,

tensor([[     9,     30,      2,  ...,     35,      0,     15],
        [   200,     41,  27718,  ...,      9,     30,      9],
        [    10,      6,    160,  ...,     90,      5,    986],
        ...,
        [   805,      6,    222,  ...,      1,      1,      1],
        [    44,     28,  27718,  ...,      1,      1,      1],
        [  4917,      0,  18573,  ...,      1,      1,      1]]) tensor([ 0,  1,  1,  1,  0,  1,  1,  1,  1,  0,  0,  0,  0,  1,
         0,  0,  0,  1,  1,  1,  1,  1,  0,  0,  1,  0,  0,  1,
         1,  0,  1,  1])
tensor([[    57,   9252,      9,  ...,    144,    427,     10],
        [ 44605,     14,   4202,  ...,     54,     19,     14],
        [    16,    222,     11,  ...,   3284,      2,     30],
        ...,
        [    13,      5,     83,  ...,      1,      1,      1],
        [     0,      2,   9370,  ...,      1,      1,      1],
        [ 31340,      0,      0,  ...,      1,      1,      1]]) tensor([ 0,  1,  1,  1,  1,  0,  0,  0,  0,  1,  1,

/Users/sangjunyum/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:5: DeprecationWarning: generator 'Iterator.__iter__' raised StopIteration


In [179]:
print(val_loss, val_accuracy)

tensor(3.6658) tensor(49)


In [ ]:
epoch_order = 0
best_val_accuracy = -1
best_val_loss = 0

for copy_model in models:
    if copy_model[2]> best_val_accuracy:
        epoch_order = copy_model[0]
        best_val_loss = copy_model[1]
        best_val_accuracy = copy_model[2]
        model = copy_model[3]

In [240]:
print("[!] saving model")
print("Best Validation Loss: %5.2f | Best Validation Accuracy: %5.2f", %())
if not os.path.isdir("snapshot"):
    os.makedirs("snapshot")
    torch.save(model.state_dict(), './snapshot/%d_convcnn.pt' % (epoch_order))

SyntaxError: invalid syntax (<ipython-input-240-b7950cb47c7b>, line 2)

In [ ]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
print(input.shape)
print(target.shape)

In [27]:
print(vocab_size)

46159
